export type ModuleMeta = {
  slug: string;
  path: string;
  name: string;
  methods: string;
  group: string;
  keywords: string[];
  api: string;
  enabled: boolean;
};

const WAVE1 = new Set(["lp", "transport", "networks", "pert-cpm", "queues"]);

export const MODULE_GROUPS = [
  "Optimización",
  "Redes y flujo",
  "Proyectos",
  "Aleatoriedad y espera",
  "Inventarios y producción",
  "Predicción y decisión",
  "Calidad y estadística",
] as const;

export const MODULES: ModuleMeta[] = [
  {
    slug: "lp",
    path: "/lp",
    name: "Programación lineal",
    methods: "Simplex, sensibilidad, gráfico con 2 variables",
    group: "Optimización",
    keywords: ["lp", "simplex", "lineal", "sensibilidad", "ranging", "precio sombra"],
    api: "lp",
    enabled: WAVE1.has("lp"),
  },
  {
    slug: "ilp",
    path: "/ilp",
    name: "Programación entera",
    methods: "Ramificación y acotamiento, enteras mixtas",
    group: "Optimización",
    keywords: ["ilp", "entera", "branch", "bound", "binaria", "mip"],
    api: "ilp",
    enabled: WAVE1.has("ilp"),
  },
  {
    slug: "goal",
    path: "/goal",
    name: "Programación por metas",
    methods: "Metas con prioridades",
    group: "Optimización",
    keywords: ["goal", "metas", "gp", "prioridades"],
    api: "goal_programming",
    enabled: WAVE1.has("goal"),
  },
  {
    slug: "qp",
    path: "/qp",
    name: "Programación cuadrática",
    methods: "Cuadrática con restricciones lineales",
    group: "Optimización",
    keywords: ["cuadrática", "qp", "quadratic"],
    api: "quadratic_programming",
    enabled: WAVE1.has("qp"),
  },
  {
    slug: "nlp",
    path: "/nlp",
    name: "Programación no lineal",
    methods: "Óptimo local y trayectoria",
    group: "Optimización",
    keywords: ["no lineal", "nlp", "nonlinear"],
    api: "nonlinear_programming",
    enabled: WAVE1.has("nlp"),
  },
  {
    slug: "dp",
    path: "/dp",
    name: "Programación dinámica",
    methods: "Mochila, diligencia por etapas",
    group: "Optimización",
    keywords: ["dp", "dinámica", "mochila", "knapsack", "stagecoach", "etapas"],
    api: "dynamic_programming",
    enabled: WAVE1.has("dp"),
  },
  {
    slug: "transport",
    path: "/transport",
    name: "Transporte",
    methods: "Vogel, noroeste, costo mínimo, MODI",
    group: "Redes y flujo",
    keywords: ["transporte", "vogel", "modi", "noroeste", "vam"],
    api: "transport",
    enabled: WAVE1.has("transport"),
  },
  {
    slug: "assignment",
    path: "/assignment",
    name: "Asignación",
    methods: "Método húngaro",
    group: "Redes y flujo",
    keywords: ["asignación", "húngaro", "hungarian"],
    api: "assignment",
    enabled: WAVE1.has("assignment"),
  },
  {
    slug: "networks",
    path: "/networks",
    name: "Redes",
    methods: "Ruta corta, árbol mínimo, flujo máximo, viajante",
    group: "Redes y flujo",
    keywords: ["redes", "dijkstra", "kruskal", "flujo", "tsp", "árbol"],
    api: "networks",
    enabled: WAVE1.has("networks"),
  },
  {
    slug: "pert-cpm",
    path: "/pert-cpm",
    name: "PERT/CPM",
    methods: "Ruta crítica, Gantt, aceleración",
    group: "Proyectos",
    keywords: ["pert", "cpm", "ruta crítica", "gantt", "proyecto", "crashing"],
    api: "pert_cpm",
    enabled: WAVE1.has("pert-cpm"),
  },
  {
    slug: "jobs",
    path: "/jobs",
    name: "Programación de tareas",
    methods: "SPT, EDD, Johnson",
    group: "Proyectos",
    keywords: ["job", "scheduling", "spt", "edd", "johnson", "makespan"],
    api: "job_scheduling",
    enabled: WAVE1.has("jobs"),
  },
  {
    slug: "queues",
    path: "/queues",
    name: "Teoría de colas",
    methods: "M/M/1, M/M/s, M/G/1, costos",
    group: "Aleatoriedad y espera",
    keywords: ["colas", "waiting", "mm1", "rho", "lq", "wq"],
    api: "queues",
    enabled: WAVE1.has("queues"),
  },
  {
    slug: "qss",
    path: "/qss",
    name: "Simulación de colas",
    methods: "Eventos discretos, réplicas",
    group: "Aleatoriedad y espera",
    keywords: ["simulación", "colas", "qss", "eventos"],
    api: "queuing_simulation",
    enabled: WAVE1.has("qss"),
  },
  {
    slug: "markov",
    path: "/markov",
    name: "Cadenas de Markov",
    methods: "Estado estable, absorbentes",
    group: "Aleatoriedad y espera",
    keywords: ["markov", "transición", "absorbente", "estado estable"],
    api: "markov",
    enabled: WAVE1.has("markov"),
  },
  {
    slug: "eoq",
    path: "/eoq",
    name: "EOQ",
    methods: "Cantidad económica de pedido",
    group: "Inventarios y producción",
    keywords: ["eoq", "pedido", "inventario básico"],
    api: "eoq",
    enabled: WAVE1.has("eoq"),
  },
  {
    slug: "inventory",
    path: "/inventory",
    name: "Inventarios",
    methods: "EOQ, descuentos, EPQ, vendedor de periódicos",
    group: "Inventarios y producción",
    keywords: ["inventario", "epq", "newsvendor", "wagner", "backorder"],
    api: "inventory",
    enabled: WAVE1.has("inventory"),
  },
  {
    slug: "mrp",
    path: "/mrp",
    name: "MRP",
    methods: "Explosión de materiales, liberaciones planeadas",
    group: "Inventarios y producción",
    keywords: ["mrp", "bom", "materiales"],
    api: "mrp",
    enabled: WAVE1.has("mrp"),
  },
  {
    slug: "aggregate",
    path: "/aggregate",
    name: "Planeación agregada",
    methods: "Persecución, nivel constante, mixta",
    group: "Inventarios y producción",
    keywords: ["agregada", "aggregate", "chase", "level"],
    api: "aggregate_planning",
    enabled: WAVE1.has("aggregate"),
  },
  {
    slug: "facility",
    path: "/facility",
    name: "Localización y layout",
    methods: "Centro de gravedad, balanceo de línea",
    group: "Inventarios y producción",
    keywords: ["localización", "layout", "gravedad", "balanceo"],
    api: "facility_location",
    enabled: WAVE1.has("facility"),
  },
  {
    slug: "forecasting",
    path: "/forecasting",
    name: "Pronósticos",
    methods: "Media móvil, Holt, Winters, tendencia",
    group: "Predicción y decisión",
    keywords: ["pronóstico", "holt", "winters", "mape", "forecast"],
    api: "forecasting",
    enabled: WAVE1.has("forecasting"),
  },
  {
    slug: "decision",
    path: "/decision",
    name: "Análisis de decisiones",
    methods: "Tabla de pagos, árbol, Bayes, Hurwicz",
    group: "Predicción y decisión",
    keywords: ["decisión", "árbol", "emv", "evpi", "hurwicz", "bayes"],
    api: "decision_analysis",
    enabled: WAVE1.has("decision"),
  },
  {
    slug: "game",
    path: "/game",
    name: "Teoría de juegos",
    methods: "Punto silla, estrategias mixtas",
    group: "Predicción y decisión",
    keywords: ["juegos", "silla", "mixta", "dominada"],
    api: "game_theory",
    enabled: WAVE1.has("game"),
  },
  {
    slug: "quality",
    path: "/quality",
    name: "Control de calidad",
    methods: "Cartas X̄-R, p, c, u; Cp/Cpk",
    group: "Calidad y estadística",
    keywords: ["calidad", "carta", "xbar", "cpk", "control"],
    api: "quality_control",
    enabled: WAVE1.has("quality"),
  },
  {
    slug: "asa",
    path: "/asa",
    name: "Muestreo de aceptación",
    methods: "Curva OC, AOQ, diseño de plan",
    group: "Calidad y estadística",
    keywords: ["muestreo", "asa", "oc", "aql", "ltpd"],
    api: "acceptance_sampling",
    enabled: WAVE1.has("asa"),
  },
  {
    slug: "statistics",
    path: "/statistics",
    name: "Estadística",
    methods: "Descriptiva, regresión, pruebas, distribuciones",
    group: "Calidad y estadística",
    keywords: ["estadística", "regresión", "ttest", "normal"],
    api: "statistics",
    enabled: WAVE1.has("statistics"),
  },
  {
    slug: "breakeven",
    path: "/breakeven",
    name: "Punto de equilibrio",
    methods: "Costo-volumen-utilidad, alternativas",
    group: "Calidad y estadística",
    keywords: ["equilibrio", "breakeven", "cvp", "contribución"],
    api: "breakeven",
    enabled: WAVE1.has("breakeven"),
  },
];

export function searchModules(query: string, opts?: { includeSoon?: boolean }): ModuleMeta[] {
  const pool = opts?.includeSoon ? MODULES : MODULES.filter((m) => m.enabled);
  const q = query.trim().toLowerCase();
  if (!q) return pool;
  return pool.filter((m) => {
    const hay = [m.name, m.methods, m.group, ...m.keywords].join(" ").toLowerCase();
    return hay.includes(q) || q.split(/\s+/).every((tok) => hay.includes(tok));
  });
}

export function moduleByPath(path: string): ModuleMeta | undefined {
  return MODULES.find((m) => m.path === path || m.slug === path.replace(/^\//, ""));
}
