const LABELS: Record<string, string> = {
  module: "módulo",
  status: "estado",
  variable: "variable",
  value: "valor",
  objective_value: "valor objetivo",
  objective_sense: "sentido del objetivo",
  metric: "métrica",
  metrics: "métricas",
  warnings: "advertencias",
  index: "índice",
  method: "método",
  title: "título",
  meta: "meta",
  shadow_prices: "precios sombra",
  reduced_costs: "costos reducidos",
  objective_ranges: "rangos de optimalidad",
  rhs_ranges: "rangos de factibilidad",
  constraint_analysis: "análisis de restricciones",
  lhs: "lado izquierdo",
  sense: "sentido",
  rhs: "lado derecho",
  slack_or_surplus: "holgura o exceso",
  shadow_price: "precio sombra",
  allowable_min_rhs: "LD mín. permitido",
  allowable_max_rhs: "LD máx. permitido",
  coeff: "coef. actual",
  reduced_cost: "costo reducido",
  min_coef: "coef. mínimo",
  max_coef: "coef. máximo",
  allowable_increase: "aumento permitido",
  allowable_decrease: "disminución permitida",
  schedule: "cronograma",
  actividad: "actividad",
  duracion: "duración",
  es: "inicio temprano (ES)",
  ef: "fin temprano (EF)",
  ls: "inicio tardío (LS)",
  lf: "fin tardío (LF)",
  critica: "crítica",
  optimista: "optimista (a)",
  probable: "más probable (m)",
  pesimista: "pesimista (b)",
  project_duration: "duración del proyecto",
  project_te: "tiempo esperado (te)",
  project_variance: "varianza del proyecto",
  project_std: "desviación estándar",
  prob_meet_target: "probabilidad de cumplir el objetivo",
  crash_total_cost: "costo extra de aceleración",
  crash_target: "duración objetivo",
  project_cost: "costo del proyecto",
  critical_path_count: "rutas críticas",
  critical_path: "ruta crítica",
  gantt: "gantt",
  flows: "flujos",
  min_cut: "corte mínimo",
  vertices_feasible: "Vértices de la región factible",
  optimo: "óptimo",
  infeasible: "infactible",
  unbounded: "no acotado",
  min: "minimización",
  max: "maximización",
  durations_after_crash: "Duraciones tras aceleración",
  cost_by_s: "costo por número de servidores",
  Pn: "Pn",
  path_length: "longitud de la ruta",
  mst_weight: "peso del árbol mínimo",
  max_flow: "flujo máximo",
  min_cut_value: "valor del corte mínimo",
  tour_length: "longitud del recorrido",
  total_cost: "costo total",
  assignment: "asignación",
  sin_asignar: "sin asignar",
  asignacion_alternativa: "asignación alternativa",
  matriz_original: "matriz original (M = prohibida)",
  agente: "agente",
  tarea: "tarea",
  ganancia: "ganancia",
  costo: "costo",
  tipo: "tipo",
  nombre: "nombre",
  total: "total",
  n_assignments: "parejas asignadas",
  n_adjustments: "ajustes de la matriz",
  costo_unitario: "costo unitario",
  peso: "peso",
  ruta: "ruta",
  aristas_mst: "aristas del árbol mínimo",
  recorrido: "recorrido",
  lambda: "tasa de llegada (λ)",
  mu: "tasa de servicio (μ)",
  rho: "utilización (ρ)",
  Lq: "clientes en cola (Lq)",
  L: "clientes en el sistema (L)",
  Wq: "espera en cola (Wq)",
  W: "espera en el sistema (W)",
  P0: "prob. sistema vacío (P0)",
  lambda_eff: "tasa efectiva de llegada (λeff)",
  cost_waiting: "costo de espera",
  cost_server: "costo de servidores",
  cost_total: "costo total",
  servidores: "servidores",
  Pw: "prob. de esperar (Pw)",
  r: "carga ofrecida (λ/μ)",
  servers: "servidores (s)",
  busy_servers: "servidores ocupados (promedio)",
  idle_servers: "servidores libres (promedio)",
  P_block: "prob. de sistema lleno (PK)",
  lambda_lost: "clientes rechazados por unidad de tiempo",
  customers_outside: "clientes fuera del sistema (N - L)",
  cv_service: "coef. de variación del servicio",
  s_min_stable: "servidores mínimos para estabilidad",
  t: "tiempo t",
  P_wq_gt_t: "P(Wq > t)",
  P_w_gt_t: "P(W > t)",
  s_optimal: "número óptimo de servidores",
  cost_total_optimal: "costo total con s óptimo",
  acumulada: "acumulada",
  formulas: "fórmulas",
  medida: "medida",
  formula: "fórmula",
  sustitucion: "sustitución",
  valor: "valor",
  unidad: "unidad",
  curva_congestion: "curva de congestión",
  datos: "datos del problema",
  parametro: "parámetro",
  clave: "clave",
  costo_espera: "costo de espera",
  costo_servidor: "costo de servidores",
  costo_total: "costo total",
  óptimo: "óptimo",
  Q_star: "cantidad económica de pedido (Q*)",
  orders_per_year: "pedidos por año",
  time_between_orders_years: "tiempo entre pedidos (años)",
  time_between_orders_days: "tiempo entre pedidos (días)",
  avg_inventory: "inventario promedio",
  TC_ordering: "costo anual de ordenar",
  TC_holding: "costo anual de mantener",
  relevant_cost: "costo relevante (ordenar + mantener)",
  purchase_cost: "costo anual de compra",
  TC: "costo total",
  daily_demand: "demanda diaria",
  lead_time: "tiempo de entrega (días)",
  reorder_point: "punto de reorden",
  costos: "costos",
  envios: "envíos",
  resumen_origenes: "resumen por origen",
  resumen_destinos: "resumen por destino",
  origen: "origen",
  destino: "destino",
  cantidad: "cantidad",
  subtotal: "subtotal",
  oferta: "oferta",
  enviado: "enviado",
  sin_enviar: "sin enviar",
  demanda: "demanda",
  recibido: "recibido",
  faltante: "faltante",
  basic_cells: "rutas con envío",
  routes_used: "rutas usadas",
  units_shipped: "unidades enviadas",
  unused_supply: "oferta sin enviar",
  unmet_demand: "demanda sin cubrir",
  modi_iterations: "iteraciones MODI",
  optimal_cost: "valor óptimo (MODI)",
  gap: "diferencia contra el óptimo",
  summary: "resumen",
};

export function labelKey(key: string): string {
  const k = key.trim();
  if (!k) return "—";
  if (LABELS[k]) return LABELS[k];
  const lower = k.toLowerCase();
  if (LABELS[lower]) return LABELS[lower];
  return k.replaceAll("_", " ");
}

export function labelColumns(columns: string[]): string[] {
  return columns.map(labelKey);
}

export function labelTableName(name: string): string {
  return labelKey(name);
}
