"""Etiquetas en español para exportaciones PDF/Excel."""

from __future__ import annotations

LABELS: dict[str, str] = {
    "module": "módulo",
    "status": "estado",
    "variable": "variable",
    "value": "valor",
    "objective_value": "valor objetivo",
    "objective_sense": "sentido del objetivo",
    "metric": "métrica",
    "metrics": "métricas",
    "warnings": "advertencias",
    "index": "índice",
    "method": "método",
    "title": "título",
    "meta": "meta",
    "section": "sección",
    "payload": "contenido",
    "shadow_prices": "precios sombra",
    "reduced_costs": "costos reducidos",
    "objective_ranges": "rangos de optimalidad",
    "rhs_ranges": "rangos de factibilidad",
    "Solution": "Solución",
    "Iterations": "Iteraciones",
    "Sensitivity": "Sensibilidad",
    "Table": "Tabla",
    "schedule": "cronograma",
    "critical_path": "ruta crítica",
    "gantt": "gantt",
    "decisions": "decisiones",
    "payoff": "matriz de pagos",
    "matriz_pagos": "matriz de pagos",
    "tree_fold": "árbol plegado",
    "bayes": "análisis de Bayes",
    "maximax": "máximax",
    "maximin": "máximin",
    "minimax_regret": "mínimo arrepentimiento",
    "hurwicz": "Hurwicz",
    "laplace": "Laplace",
    "expected_value": "valor esperado",
    "EOL_choice": "mejor arrepentimiento esperado",
    "EV": "valor esperado (VE)",
    "EVwPI": "VE con información perfecta",
    "EVPI": "valor de la información perfecta",
    "EVwSI": "VE con información muestral",
    "EVSI": "valor de la información muestral",
    "EOL": "arrepentimiento esperado",
    "signal": "señal",
    "best_action": "mejor acción",
    "best_prior_action": "mejor acción (sin muestra)",
    "current_best": "mejor alternativa actual",
    "competitor": "competidor",
    "breakeven_probability_state1": "punto de indiferencia P(estado 1)",
    "decision": "decisión",
    "chance": "azar",
    "terminal": "terminal",
    "tipo": "tipo",
    "mejor_hijo": "mejor hijo",
    "forecasts": "pronósticos",
    "best_method": "mejor método",
    "error_comparison": "comparación de errores",
    "flows": "flujos",
    "min_cut": "corte mínimo",
    "sequence": "secuencia",
    "jobs": "trabajos",
    "summary": "resumen",
    "transient": "estados transitorios",
    "steady_state": "estado estacionario",
    "fundamental_matrix": "matriz fundamental",
    "absorption_probabilities": "probabilidades de absorción",
    "expected_steps_to_absorption": "pasos esperados hasta absorción",
    "path": "ruta",
    "selected": "seleccionados",
    "stage_decisions": "decisiones por etapa",
    "bb_nodes": "nodos de ramificación y acotamiento",
    "oc_aoq": "curva OC y AOQ",
    "xbar_r": "carta X̄–R",
    "p_chart": "carta p",
    "c_chart": "carta c",
    "u_chart": "carta u",
    "ES": "IT",
    "EF": "FT",
    "LS": "ITa",
    "LF": "FTa",
    "slack": "holgura",
    "critical": "crítica",
    "te": "tiempo esperado",
    "variance": "varianza",
    "order": "orden",
    "job": "trabajo",
    "start": "inicio",
    "completion": "fin",
    "tardiness": "retraso",
    "end": "fin",
    "period": "periodo",
    "demand": "demanda",
    "workforce": "fuerza laboral",
    "hire": "contrataciones",
    "fire": "despidos",
    "production": "producción",
    "inventory": "inventario",
    "shortage": "faltante",
    "criterion": "criterio",
    "alternative": "alternativa",
    "source": "origen",
    "target": "destino",
    "flow": "flujo",
    "capacity": "capacidad",
    "unit_cost": "costo unitario",
    "cost": "costo",
    "UCL": "LSC",
    "LCL": "LIC",
    "OOC": "fuera de control",
    "subgroup": "subgrupo",
    "sample": "muestra",
    "term": "término",
    "beta": "coeficiente",
    "row": "fila",
    "node": "nodo",
    "item": "ítem",
    "stage": "etapa",
    "state": "estado",
    "optimal": "óptimo",
    "infeasible": "infactible",
    "unbounded": "no acotado",
    "feasible": "factible",
    "min": "minimización",
    "max": "maximización",
}


def label_key(key: str) -> str:
    k = key.strip()
    if not k:
        return "—"
    if k in LABELS:
        return LABELS[k]
    lower = k.lower()
    if lower in LABELS:
        return LABELS[lower]
    if k.startswith("P") and k[1:].isdigit():
        return f"periodo {k[1:]}"
    return k.replace("_", " ")


def label_columns(columns: list[str]) -> list[str]:
    return [label_key(c) for c in columns]


def label_table_name(name: str) -> str:
    return label_key(name)
